sudo: required
services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t rselva/fib-calc-client ./client

script:
  - docker run -e CI=true rselva/fib-calc-client yarn test

after_success:
  - docker build -t rselva/fib-calc-client ./client
  - docker build -t rselva/fib-calc-nginx ./nginx
  - docker build -t rselva/fib-calc-server ./server
  - docker build -t rselva/fib-calc-worker ./worker
  - echo "${DOCKER_PASSWORD}" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rselva/fib-calc-client
  - docker push rselva/fib-calc-nginx
  - docker push rselva/fib-calc-server
  - docker push rselva/fib-calc-worker
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-us-east-1-691255507802"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
#     script:
#       - docker run -e CI=true USERNAME/react-test npm test